server:
  port: 9000

eureka:
  client:
    instance:
      preferIpAddress: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: profile-server
          uri: lb://profile-server
          predicates:
            - Path=/profile/**
        - id: summary-server
          uri: http://localhost:12000/
          predicates:
            - Path=/summary/**
        - id: timesheet-server
          uri: lb://timesheet-server
          predicates:
            - Path=/timesheet/**